[project]
name = "vae-torch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pamiq-core"
]

[tool.uv.sources]
pamiq-core = { path = "../../" }
