services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pamiq-core:/workspace
      - poetry_cache:/root/.cache/pypoetry
      - pip_cache:/root/.cache/pip
    tty: true
    stdin_open: true
    command: /bin/bash
    working_dir: /workspace

volumes:
  pamiq-core:
    name: pamiq-core
  poetry_cache:
  pip_cache:
