name: Test on GPU

on:
  push:
    branches: [main, released]
  pull_request:
    branches: [main, released]

env:
  PYTHON_VERSION: "3.12"
  UV_VERSION: "0.5.10"

jobs:
  test:
    runs-on:
      - codebuild-pamiq-core-linux-gpu-runner-${{ github.run_id }}-${{ github.run_attempt }}
    strategy:
      fail-fast: false

    timeout-minutes: 20

    steps:
      - name: Show PCi
        run: lspci
      - name: Check NVIDIA GPU driver
        run: |
          if ! command -v nvidia-smi &> /dev/null; then
            echo "ERROR: NVIDIA GPU driver not found! This workflow requires NVIDIA GPU."
            echo "Please check your self-hosted runner configuration."
            exit 1
          fi
          echo "==== NVIDIA Driver Information ===="
          nvidia-smi
          echo "=================================="

      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra torch

      - name: Check installed packages
        run: |
          echo "Python version:"
          uv run python -V
          echo "All installed packages:"
          uv pip list

      - name: Run pytest
        run: |
          uv run pytest -v --log-level=INFO tests/pamiq_core/torch/
